name: netlify-branch-deploy
on:
  workflow_dispatch:
    inputs:
      deploy_id:
        required: false
        type: string
      message:
        required: false
        type: string
        description: Add a message to send to Netlify build
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: [self-hosted, netlify/build]
    strategy:
      matrix:
        STOREFRONT: ${{ vars.STOREFRONTS && fromJSON(vars.STOREFRONTS) || fromJSON('["0"]')}}
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploy to StoreFront -> ${{ matrix.STOREFRONT }}"
      - uses: packdigital/backpack-build-action@main
        with:
          deploy_id: ${{ github.event.inputs.deploy_id }}
          message: ${{ github.event.inputs.message }}
          branch: ${{ github.head_ref || github.ref_name }}
          backpack_api_secret_token: ${{ secrets[format('BACKPACK_API_SECRET_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('BACKPACK_API_SECRET_TOKEN_{0}', matrix.STOREFRONT)] || secrets.BACKPACK_API_SECRET_TOKEN }}
          backpack_site_id: ${{ secrets[format('BACKPACK_SITE_ID_{0}', matrix.STOREFRONT)] != '' && secrets[format('BACKPACK_SITE_ID_{0}', matrix.STOREFRONT)] || secrets.BACKPACK_SITE_ID }}
          cms_content_token: ${{ secrets[format('CMS_CONTENT_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('CMS_CONTENT_TOKEN_{0}', matrix.STOREFRONT)] || secrets.CMS_CONTENT_TOKEN }}
          cms_management_token: ${{ secrets[format('CMS_MANAGEMENT_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('CMS_MANAGEMENT_TOKEN_{0}', matrix.STOREFRONT)] || secrets.CMS_MANAGEMENT_TOKEN }}
          npm_auth_token: ${{ secrets[format('NPM_AUTH_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('NPM_AUTH_TOKEN_{0}', matrix.STOREFRONT)] || secrets.NPM_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets[format('NETLIFY_SITE_ID_{0}', matrix.STOREFRONT)] != '' && secrets[format('NETLIFY_SITE_ID_{0}', matrix.STOREFRONT)] || secrets.NETLIFY_SITE_ID }}
          netlify_auth_token: ${{ secrets[format('NETLIFY_AUTH_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('NETLIFY_AUTH_TOKEN_{0}', matrix.STOREFRONT)] || secrets.NETLIFY_AUTH_TOKEN }}
          shopify_domain: ${{ secrets[format('SHOPIFY_DOMAIN_{0}', matrix.STOREFRONT)] != '' && secrets[format('SHOPIFY_DOMAIN_{0}', matrix.STOREFRONT)] || secrets.SHOPIFY_DOMAIN }}
          shopify_admin_api_token: ${{ secrets[format('SHOPIFY_ADMIN_API_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('SHOPIFY_ADMIN_API_TOKEN_{0}', matrix.STOREFRONT)] || secrets.SHOPIFY_ADMIN_API_TOKEN }}
          shopify_storefront_api_token: ${{ secrets[format('SHOPIFY_STOREFRONT_API_TOKEN_{0}', matrix.STOREFRONT)] != '' && secrets[format('SHOPIFY_STOREFRONT_API_TOKEN_{0}', matrix.STOREFRONT)] || secrets.SHOPIFY_STOREFRONT_API_TOKEN }}
          site_url: ${{ secrets[format('SITE_URL_{0}', matrix.STOREFRONT)] != '' && secrets[format('SITE_URL_{0}', matrix.STOREFRONT)] || secrets.SITE_URL }}${{secrets.SITE_URL}}
          pack_api_url: ${{ secrets[format('PACK_API_URL_{0}', matrix.STOREFRONT)] != '' && secrets[format('PACK_API_URL_{0}', matrix.STOREFRONT)] || secrets.PACK_API_URL }}
          auto_deploy_netlify_disabled: ${{ secrets[format('AUTO_DEPLOY_NETLIFY_DISABLED_{0}', matrix.STOREFRONT)] != '' && secrets[format('AUTO_DEPLOY_NETLIFY_DISABLED_{0}', matrix.STOREFRONT)] || secrets.AUTO_DEPLOY_NETLIFY_DISABLED }}
          slack_webhook: ${{ secrets[format('BACKPACK_BUILD_ACTIONS_SLACK_WEBHOOK_{0}', matrix.STOREFRONT)] != '' && secrets[format('BACKPACK_BUILD_ACTIONS_SLACK_WEBHOOK_{0}', matrix.STOREFRONT)] || secrets.BACKPACK_BUILD_ACTIONS_SLACK_WEBHOOK }}